[theme]
primaryColor = "#F4B400"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F8FB"
textColor = "#0F1419"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
